[2023-05-21 10:36:44 - ERROR] - getWSGIEndpointStatus: Error validating endpoint localhost:5000 : HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /getAgentStatus (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe51c429650>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2023-05-21 10:36:44 - WARNING] - endpointStatusLoop: localhost:5000 has gone offline
[2023-05-21 10:36:54 - ERROR] - getWSGIEndpointStatus: Error validating endpoint localhost:5000 : HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /getAgentStatus (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe51c42b3d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2023-05-21 10:37:04 - ERROR] - getWSGIEndpointStatus: Error validating endpoint localhost:5000 : HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /getAgentStatus (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe51c431890>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2023-05-21 10:37:14 - ERROR] - getWSGIEndpointStatus: Error validating endpoint localhost:5000 : HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /getAgentStatus (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe51c433bd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2023-05-21 10:37:24 - ERROR] - getWSGIEndpointStatus: Error validating endpoint localhost:5000 : HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /getAgentStatus (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe51c445ed0>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2023-05-21 10:37:34 - INFO] - endpointStatusLoop: localhost:5000 has come online
[2023-05-21 10:39:55 - ERROR] - getWSGIEndpointStatus: Error validating endpoint localhost:5000 : HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /getAgentStatus (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe51c42b410>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2023-05-21 10:39:55 - WARNING] - endpointStatusLoop: localhost:5000 has gone offline
[2023-05-21 10:40:05 - ERROR] - getWSGIEndpointStatus: Error validating endpoint localhost:5000 : HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /getAgentStatus (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe51c429290>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2023-05-21 10:40:15 - ERROR] - getWSGIEndpointStatus: Error validating endpoint localhost:5000 : HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /getAgentStatus (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe51c446790>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2023-05-21 10:40:25 - ERROR] - getWSGIEndpointStatus: Error validating endpoint localhost:5000 : HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /getAgentStatus (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe51c4546d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2023-05-21 10:40:35 - ERROR] - getWSGIEndpointStatus: Error validating endpoint localhost:5000 : HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /getAgentStatus (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe51c456ad0>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2023-05-21 10:40:45 - ERROR] - getWSGIEndpointStatus: Error validating endpoint localhost:5000 : HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /getAgentStatus (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe51c45ce50>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2023-05-21 10:40:55 - ERROR] - getWSGIEndpointStatus: Error validating endpoint localhost:5000 : HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /getAgentStatus (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe51c455590>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2023-05-21 10:41:05 - INFO] - endpointStatusLoop: localhost:5000 has come online
[2023-05-21 10:45:41 - ERROR] - getWSGIEndpointStatus: Error validating endpoint localhost:5000 : HTTPConnectionPool(host='localhost', port=5000): Read timed out. (read timeout=5)
[2023-05-21 10:45:41 - WARNING] - endpointStatusLoop: localhost:5000 has gone offline
[2023-05-21 10:45:51 - ERROR] - getWSGIEndpointStatus: Error validating endpoint localhost:5000 : HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /getAgentStatus (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe51c428ed0>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2023-05-21 10:46:01 - INFO] - endpointStatusLoop: localhost:5000 has come online
[2023-05-21 10:51:12 - ERROR] - getWSGIEndpointStatus: Error validating endpoint localhost:5000 : HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /getAgentStatus (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fec6f733e50>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2023-05-21 10:51:12 - WARNING] - endpointStatusLoop: localhost:5000 has gone offline
[2023-05-21 10:51:22 - INFO] - endpointStatusLoop: localhost:5000 has come online
